version: '3'
services:
  db: 
    image: postgres
    environment:
      POSTGRES_DB: helping_community_development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports:
      - "3306"
    expose:
      - "3306"
  web: 
    build: .
    volumes: 
      - .:/docker-rails
      - bundler_gems:/usr/local/bundle
    ports:
    - "3000:3000"
    depends_on: 
      - db
volumes:
  postgres:
  bundler_gems: 
