version: '3'
services:
  db: 
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - postgres:/var/lib/postgresql/data
  web: 
    build: .
    volumes: 
      - .:/myapp
      - bundler_gems:/usr/local/bundle
    ports:
    - "3000:3000"
    depends_on: 
      - db
volumes:
  postgres:
  bundler_gems: 