---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/hello":
    get:
      summary: Get the Home#HelloWorld
      tags:
      - Home
      consumes:
      - application/json
      responses:
        '201':
          description: You get the hello world!
          schema:
            type: object
            properties:
              msg:
                type: string
