---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: Get the Home#index
      tags:
      - Home
      consumes:
      - application/json
      responses:
        '201':
          description: You get the index
          schema:
            type: object
            properties:
              hello_world:
                type: string
